//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PuntoDeVentaAlm.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ALMENDRITAEntities : DbContext
    {
        public ALMENDRITAEntities()
            : base("name=ALMENDRITAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBL_CATALOGO_LOG> TBL_CATALOGO_LOG { get; set; }
        public virtual DbSet<TBL_DETALLES_INVENT> TBL_DETALLES_INVENT { get; set; }
        public virtual DbSet<TBL_INVENTARIOS> TBL_INVENTARIOS { get; set; }
        public virtual DbSet<TBL_LOG> TBL_LOG { get; set; }
        public virtual DbSet<TBL_LOG_ERROR> TBL_LOG_ERROR { get; set; }
        public virtual DbSet<TBL_PRODUCTOS> TBL_PRODUCTOS { get; set; }
        public virtual DbSet<TBL_STOCK> TBL_STOCK { get; set; }
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<TBL_LOTE_PRODUCCION> TBL_LOTE_PRODUCCION { get; set; }
        public virtual DbSet<TBL_DETALLE_LOTE> TBL_DETALLE_LOTE { get; set; }
        public virtual DbSet<TBL_PRESENTACIONES_PRODUCT> TBL_PRESENTACIONES_PRODUCT { get; set; }
        public virtual DbSet<TBL_CLIENTES> TBL_CLIENTES { get; set; }
        public virtual DbSet<TBL_ALMACENES> TBL_ALMACENES { get; set; }
        public virtual DbSet<TBL_DIRECCIONES> TBL_DIRECCIONES { get; set; }
        public virtual DbSet<TBL_SOCIEDADES> TBL_SOCIEDADES { get; set; }
        public virtual DbSet<TBL_SUCURSALES> TBL_SUCURSALES { get; set; }
    }
}
