//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PuntoDeVentaAlm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_PRODUCTOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_PRODUCTOS()
        {
            this.TBL_STOCK = new HashSet<TBL_STOCK>();
            this.TBL_LOTE_PRODUCCION = new HashSet<TBL_LOTE_PRODUCCION>();
            this.TBL_PRESENTACIONES_PRODUCT = new HashSet<TBL_PRESENTACIONES_PRODUCT>();
            this.TBL_DETALLES_INVENT = new HashSet<TBL_DETALLES_INVENT>();
        }
    
        public string ID_PRODUCTO { get; set; }
        public string DESCRIPCION { get; set; }
        public Nullable<float> PRECIO { get; set; }
        public Nullable<float> IVA { get; set; }
        public Nullable<float> IEPS { get; set; }
        public string U_MEDIDA { get; set; }
        public string CLAVE_SAT { get; set; }
        public Nullable<System.DateTime> FECHA_ALTA { get; set; }
        public Nullable<bool> ESTATUS { get; set; }
        public Nullable<float> ULTIM_PRECIO_COMPRA { get; set; }
        public Nullable<bool> PRODUCTO_PROPIO { get; set; }
        public string ID_USER_ASP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_STOCK> TBL_STOCK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_LOTE_PRODUCCION> TBL_LOTE_PRODUCCION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_PRESENTACIONES_PRODUCT> TBL_PRESENTACIONES_PRODUCT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_DETALLES_INVENT> TBL_DETALLES_INVENT { get; set; }
    }
}
