//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PuntoDeVentaAlm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_CLIENTES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_CLIENTES()
        {
            this.TBL_DIRECCIONES = new HashSet<TBL_DIRECCIONES>();
        }
    
        public int ID_CLIENTE { get; set; }
        public string RAZON_SOCIAL { get; set; }
        public string RFC { get; set; }
        public Nullable<System.DateTime> FECHA_ALTA { get; set; }
        public Nullable<float> LIMITE_CREDITO { get; set; }
        public Nullable<byte> DIAS_CREDITO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_DIRECCIONES> TBL_DIRECCIONES { get; set; }
    }
}
