//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PuntoDeVentaAlm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_LOG_ERROR
    {
        public int ID_ERROR { get; set; }
        public string DESCRIPCION { get; set; }
        public Nullable<System.DateTime> FECHA_ERROR { get; set; }
        public string ERROR_EXCEPTION { get; set; }
        public int ID_USU { get; set; }
    }
}
