//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PuntoDeVentaAlm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_PRESENTACIONES_PRODUCT
    {
        public int ID_PRESENCTACION { get; set; }
        public string DESCRIPCION { get; set; }
        public Nullable<float> UNIDADES { get; set; }
        public string ID_PRODUCTO { get; set; }
    
        public virtual TBL_PRODUCTOS TBL_PRODUCTOS { get; set; }
    }
}
