//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PuntoDeVentaAlm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_DIRECCIONES
    {
        public int ID_DIRECCION { get; set; }
        public string CALLE { get; set; }
        public string NUMERO { get; set; }
        public string COLONIA { get; set; }
        public string MUNICIPIO { get; set; }
        public string ESTADO { get; set; }
        public string PAIS { get; set; }
        public string CP { get; set; }
        public string TELEFONO { get; set; }
        public string CORREO { get; set; }
        public int ID_CLIENTE { get; set; }
    
        public virtual TBL_CLIENTES TBL_CLIENTES { get; set; }
    }
}
