//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PuntoDeVentaAlm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_LOG
    {
        public int ID_LOG { get; set; }
        public int ID_USU { get; set; }
        public int ID_CAT_LOG { get; set; }
        public Nullable<System.DateTime> FECHA_LOG { get; set; }
        public string DETALLE { get; set; }
    
        public virtual TBL_CATALOGO_LOG TBL_CATALOGO_LOG { get; set; }
    }
}
