//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PuntoDeVentaAlm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_ALMACENES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_ALMACENES()
        {
            this.TBL_STOCK = new HashSet<TBL_STOCK>();
            this.TBL_INVENTARIOS = new HashSet<TBL_INVENTARIOS>();
        }
    
        public int ID_ALMACEN { get; set; }
        public string NOM_ALMACEN { get; set; }
        public string ESTADO { get; set; }
        public string CALLE { get; set; }
        public Nullable<short> NUMERO { get; set; }
        public string COLONIA { get; set; }
        public string CP { get; set; }
        public Nullable<bool> ESTATUS { get; set; }
        public Nullable<System.DateTime> FECHA_REGISTRO_ALMACEN { get; set; }
        public string ID_USER_ASP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_STOCK> TBL_STOCK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_INVENTARIOS> TBL_INVENTARIOS { get; set; }
    }
}
