//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PuntoDeVentaAlm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_DETALLES_INVENT
    {
        public int ID_DET_INV { get; set; }
        public Nullable<float> CANTIDAD { get; set; }
        public int ID_INVENTARIO { get; set; }
        public string ID_PRODUC { get; set; }
        public Nullable<System.DateTime> FECHA_REGISTRO_INV { get; set; }
        public string ID_USER_ASP { get; set; }
    
        public virtual TBL_INVENTARIOS TBL_INVENTARIOS { get; set; }
        public virtual TBL_PRODUCTOS TBL_PRODUCTOS { get; set; }
    }
}
