//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PuntoDeVentaAlm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_SUCURSALES
    {
        public int ID_SUCURSAL { get; set; }
        public string NOM_SUCURSAL { get; set; }
        public string PAIS { get; set; }
        public string ESTADO { get; set; }
        public string CALLE { get; set; }
        public Nullable<short> NUMERO { get; set; }
        public string COLONIA { get; set; }
        public string CP { get; set; }
        public Nullable<bool> ESTATUS { get; set; }
        public Nullable<System.DateTime> FECHA_REGISTRO_SUCURSAL { get; set; }
        public string ID_USER_ASP { get; set; }
        public string TELEFONO { get; set; }
    }
}
