//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PuntoDeVentaAlm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_LOTE_PRODUCCION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_LOTE_PRODUCCION()
        {
            this.TBL_DETALLE_LOTE = new HashSet<TBL_DETALLE_LOTE>();
        }
    
        public string ID_LOTE { get; set; }
        public Nullable<float> COSTO_PRODUCCION { get; set; }
        public Nullable<System.DateTime> FECHA_PRODUC { get; set; }
        public Nullable<System.DateTime> FECHA_REGISTRO { get; set; }
        public string ID_PRODUC { get; set; }
        public Nullable<bool> ABIERTO { get; set; }
        public string ID_USER_ASP { get; set; }
        public Nullable<bool> CANCELADO { get; set; }
        public string DESCRIPCION { get; set; }
    
        public virtual TBL_PRODUCTOS TBL_PRODUCTOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_DETALLE_LOTE> TBL_DETALLE_LOTE { get; set; }
    }
}
